### ISSUE TITLE
Change password field floating left

### ISSUE THREAD

**Issue by chocoelho** [colab/colab#116]
There's a problem when user has multiple emails. Change password field is floating left.

![update_profile_multiple_emails](https://cloud.githubusercontent.com/assets/3460435/11375771/4b42361c-92c4-11e5-9400-b9e8a03a6bbd.png)

**Comment by chaws** [comment]
Fixed by https://softwarepublico.gov.br/gitlab/softwarepublico/softwarepublico/merge_requests/238

**Comment by chocoelho** [comment]
Isn't it fixed in SPB-theme? If you only there, you don't fix it here.
