### ISSUE TITLE
When create a new email in update profile

### ISSUE THREAD

**Issue by macartur** [colab/colab#154]
The buttom 'apagar' is broken 
![email_cant_be_removed](https://cloud.githubusercontent.com/assets/2965806/12520274/bbd37564-c12a-11e5-844e-ccb02e327617.png)
The buttom 'apagar' is working when refresh the page
![can_remove_email](https://cloud.githubusercontent.com/assets/2965806/12520267/b44eb4b6-c12a-11e5-8c53-b5d79e38b6f5.png)

**Comment by chaws** [comment]
@macartur I just tested it out, and it seems to be working fine with the current version of SPB
