### ISSUE TITLE
Add a new email and delete email buttons are redirecting to user profile page

### ISSUE THREAD

**Issue by italopaiva** [colab/colab#171]
We follow the following steps:

*  We have installed and configured mailman and mailman-api;
* Then we created a new user and activated it;
* We access the user profile edit page and tried to add a new email;
* Then we get redirected to the user profile page and the new email wasn't added.
* The same occurred when try to delete an already registered email;

OBS.: The Ajax post request is not being sent when clicking the 'Add Email' or 'Delete' buttons no user profile edit page.

We talked with @chocoelho, he is aware of this.

**Comment by chaws** [comment]
@italopaiva  I just tested it out, and it seems to be working fine with version 1.13.5. Please re-open it if errors persist.

**Comment by italopaiva** [comment]
Ok, @chaws. Thanks!
