### ISSUE TITLE
Whoosh and django-haystack integration

### ISSUE THREAD

**Issue by macagua** [colab/colab#55]
Hi @seocam

We have a Whoosh and django-haystack integration as replace to the Search engine with Solr (Thanks to @overflow) for our Colab application but we would like to share as Plugin mechanism, I see the Colab docs in http://colab.readthedocs.org/en/latest/plugindev.html there is a "Plugin Developer Documentation" but without write.

There is a Draft about how create a plugin for Colab or some code to inspire me for create a Colab plugin.

**Comment by seocam** [comment]
@macagua we are currently working to stabilize/document the plugin architecture. The plugins will be able to communicate with other plugins using Colab as a bus. All in an event driven matter. For now a lot of code and not much docs... :(

On next release whoosh will also be the default search engine for Colab.
