### ISSUE TITLE
Colab plugin prefix format

### ISSUE THREAD

**Issue by rafamanzo** [colab/colab#63]
There is no documentation on how the plugin's prefix setting should be formatted.

For example, given the upstream is `http://localhost/mezuro`, prefix is `mezuro` and the request made is for `http://localhost/mezuro/repositories`. Then colab's path will be `/repositories`.

This will cause revproxy to wrongly make the request to `http://localhost/repositories`. To get the expected behaviour from revproxy, the path should be `repositories`.

In order to achieve this, then the plugin's prefix setting should be `^mezuro/`.

**Comment by seocam** [comment]
Fixed on mezuro, gitlab and noosfero.
