### ISSUE TITLE
User email validation

### ISSUE THREAD

**Issue by chaws** [colab/colab#98]
In the user interface, when user desires to add more emails to his/her account, the button "Verify" is ajax-activated and 'EmailValidationView' is invoked to send the user a validation email. But it never works since the line https://github.com/colab/colab/blob/master/colab/super_archives/views.py#L280 breaks because '''http.DoesNotExist''' (there is no 'DoesNotExist' in 'http')

**Comment by MatheusFaria** [comment]
@chaws, I think that this pull request https://github.com/colab/colab/pull/110 fix this issue

**Comment by chaws** [comment]
+1 @MatheusFaria nice!
